// <auto-generated />
using System;
using MetaReal.Infra.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MetaReal.Infra.Data.Data.Migrations
{
    [DbContext(typeof(MetaRealDbContext))]
    [Migration("20260803202628_InicialVendedoresVendas")]
    partial class InicialVendedoresVendas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MetaReal.Domain.Models.RegistroVenda", b =>
                {
                    b.Property<Guid>("IdRegistroVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CrediarioDujuca")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Garantia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IdVendedor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumVendas")
                        .HasColumnType("int");

                    b.Property<decimal>("PretasMistas")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantAtendimento")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotalVendas")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdRegistroVenda");

                    b.HasIndex("IdVendedor", "Data")
                        .IsUnique();

                    b.ToTable("RegistrosVenda");
                });

            modelBuilder.Entity("MetaReal.Domain.Models.Vendedor", b =>
                {
                    b.Property<Guid>("IdVendedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdVendedor");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("MetaReal.Domain.Models.RegistroVenda", b =>
                {
                    b.HasOne("MetaReal.Domain.Models.Vendedor", "Vendedor")
                        .WithMany("RegistrosVenda")
                        .HasForeignKey("IdVendedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("MetaReal.Domain.Models.Vendedor", b =>
                {
                    b.Navigation("RegistrosVenda");
                });
#pragma warning restore 612, 618
        }
    }
}
