// <auto-generated />
using System;
using MetaReal.Infra.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MetaReal.Infra.Data.Data.Migrations
{
    [DbContext(typeof(MetaRealDbContext))]
    [Migration("20260805044620_AdicionarMetaVenda")]
    partial class AdicionarMetaVenda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MetaReal.Domain.Models.AuditLog", b =>
                {
                    b.Property<Guid>("IdAuditLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalhes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdEntidade")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UsuarioNome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAuditLog");

                    b.HasIndex("DataHora");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MetaReal.Domain.Models.MetaVenda", b =>
                {
                    b.Property<Guid>("IdMetaVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdVendedor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<bool>("NotificadoConclusao")
                        .HasColumnType("bit");

                    b.Property<decimal>("ValorMeta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdMetaVenda");

                    b.HasIndex("IdVendedor", "Mes", "Ano")
                        .IsUnique();

                    b.ToTable("MetasVenda");
                });

            modelBuilder.Entity("MetaReal.Domain.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("IdRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CriadoPorIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdRefreshToken");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MetaReal.Domain.Models.RegistroVenda", b =>
                {
                    b.Property<Guid>("IdRegistroVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CrediarioDujuca")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Garantia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IdVendedor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumVendas")
                        .HasColumnType("int");

                    b.Property<decimal>("PretasMistas")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantAtendimento")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotalVendas")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdRegistroVenda");

                    b.HasIndex("IdVendedor", "Data")
                        .IsUnique();

                    b.ToTable("RegistrosVenda");
                });

            modelBuilder.Entity("MetaReal.Domain.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("IdVendedor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdVendedor");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MetaReal.Domain.Models.Vendedor", b =>
                {
                    b.Property<Guid>("IdVendedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdVendedor");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("MetaReal.Domain.Models.MetaVenda", b =>
                {
                    b.HasOne("MetaReal.Domain.Models.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("IdVendedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("MetaReal.Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("MetaReal.Domain.Models.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MetaReal.Domain.Models.RegistroVenda", b =>
                {
                    b.HasOne("MetaReal.Domain.Models.Vendedor", "Vendedor")
                        .WithMany("RegistrosVenda")
                        .HasForeignKey("IdVendedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("MetaReal.Domain.Models.Usuario", b =>
                {
                    b.HasOne("MetaReal.Domain.Models.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("IdVendedor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("MetaReal.Domain.Models.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("MetaReal.Domain.Models.Vendedor", b =>
                {
                    b.Navigation("RegistrosVenda");
                });
#pragma warning restore 612, 618
        }
    }
}
